title: Vina Arny Nazira # your name (or website title) here
logo: "/image/vina.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Student undergraduated at Universitas Negeri Malang
  <br><br>
   
  <br><br>
  <a href="https://www.linkedin.com/in/vina-arny-nazira-39114026b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
